#!/usr/bin/bash
#set x
ENDFOLDER="$HOME/Desktop/animuwu/";

for i in "$@"; do
new1=$(basename "$i" | perl -pe 's/(^Kuramanime\-|A7\_)?(\-?\.?720p|\-?\.?1080p)?//g; y/_/ /; s/\.?\s?((\[|\().*?(\]|\)))+(?=.*?)\s?//g; s/(^(?:\S+\s?){1,3}).*?(\s?[e E]?\d{2})\s?.*?(\.\w{3}$)/$1$2$3/g');
mv "$i" "${ENDFOLDER}${new1}"
printf "$i\n    -> $new1\n"
done
