#!/usr/bin/bash
#RANDF=$(perl -le "print join '', map { ('a'..'z','A'..'Z',0..9,qw{- _ ! *})[rand 66] } 3..14");

ENDFOLDER="$HOME/Desktop/foldername/";

remp=$(mktemp);
trap "rm -f $remp" EXIT
wget -o - --spider "$@" | awk -F"[()]" '/Length/{print "size:"$2}'
aria2c "$@" --summary-interval=10 | tee $remp;

if grep -q "Download complete" $remp && ! grep -q "file.html" $remp
then
asd=$(cat $remp | perl -ne '/(\/home.+(mp4|mkv))/ && print ($1."\n") && exit');
new1=$(basename "$asd" | perl -pe 's/(^Kuramanime\-|A7\_)?(\-?\.?720p|\-?\.?1080p)?//g; y/_/ /; s/\.?\s?((\[|\().*?(\]|\)))+(?=.*?)\s?//g; s/(^(?:\S+\s?){1,3}).*?(\b[e E]?\d{2})\s?.*?(\.\w{3}$)/$1$2$3/g');
mv "$asd" "$ENDFOLDER$new1"
printf "$asd\n    -> $new1\n"
else
echo "Download not complete !!!!";
cat $remp;
fi

